# SQL&NoSQL
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.2:3306/pwhintek?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: 172.17.0.3
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
# MybatisPlus
mybatis-plus:
  type-aliases-package: com.pwhintek.backend # 别名扫描包
  global-config:
    db-config:
      table-prefix: t_
# 日志
logging:
  level:
    com.pwhintek.backend: debug
# Sa-token
sa-token:
  token-name: nya
  token-style: simple-uuid
  timeout: 86400